
package com;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ChatServerImplService", targetNamespace = "http://com/", wsdlLocation = "http://localhost:8081/ChatService/services/ChatServerImplPort?wsdl")
public class ChatServerImplService
    extends Service
{

    private final static URL CHATSERVERIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CHATSERVERIMPLSERVICE_EXCEPTION;
    private final static QName CHATSERVERIMPLSERVICE_QNAME = new QName("http://com/", "ChatServerImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/ChatService/services/ChatServerImplPort?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CHATSERVERIMPLSERVICE_WSDL_LOCATION = url;
        CHATSERVERIMPLSERVICE_EXCEPTION = e;
    }

    public ChatServerImplService() {
        super(__getWsdlLocation(), CHATSERVERIMPLSERVICE_QNAME);
    }

    public ChatServerImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CHATSERVERIMPLSERVICE_QNAME, features);
    }

    public ChatServerImplService(URL wsdlLocation) {
        super(wsdlLocation, CHATSERVERIMPLSERVICE_QNAME);
    }

    public ChatServerImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CHATSERVERIMPLSERVICE_QNAME, features);
    }

    public ChatServerImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ChatServerImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ChatServer
     */
    @WebEndpoint(name = "ChatServerImplPort")
    public ChatServer getChatServerImplPort() {
        return super.getPort(new QName("http://com/", "ChatServerImplPort"), ChatServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ChatServer
     */
    @WebEndpoint(name = "ChatServerImplPort")
    public ChatServer getChatServerImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://com/", "ChatServerImplPort"), ChatServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CHATSERVERIMPLSERVICE_EXCEPTION!= null) {
            throw CHATSERVERIMPLSERVICE_EXCEPTION;
        }
        return CHATSERVERIMPLSERVICE_WSDL_LOCATION;
    }

}
