
package com.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.3.13
 * Wed Apr 13 05:02:33 CST 2022
 * Generated source version: 3.3.13
 */

@XmlRootElement(name = "factorial", namespace = "http://com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "factorial", namespace = "http://com/")

public class Factorial {

    @XmlElement(name = "arg0")
    private long arg0;

    public long getArg0() {
        return this.arg0;
    }

    public void setArg0(long newArg0)  {
        this.arg0 = newArg0;
    }

}

