
package com.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.3.13
 * Mon Apr 11 05:44:16 CST 2022
 * Generated source version: 3.3.13
 */

@XmlRootElement(name = "findPrimeResponse", namespace = "http://com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "findPrimeResponse", namespace = "http://com/")

public class FindPrimeResponse {

    @XmlElement(name = "return")
    private boolean[] _return;

    public boolean[] getReturn() {
        return this._return;
    }

    public void setReturn(boolean[] new_return)  {
        this._return = new_return;
    }

}

