
package com.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.3.13
 * Wed Mar 23 17:39:40 CST 2022
 * Generated source version: 3.3.13
 */

@XmlRootElement(name = "getChatroomResponse", namespace = "http://com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getChatroomResponse", namespace = "http://com/")

public class GetChatroomResponse {

    @XmlElement(name = "return")
    private com.Chatroom[] _return;

    public com.Chatroom[] getReturn() {
        return this._return;
    }

    public void setReturn(com.Chatroom[] new_return)  {
        this._return = new_return;
    }

}

