
package com.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.3.13
 * Wed Mar 23 17:39:40 CST 2022
 * Generated source version: 3.3.13
 */

@XmlRootElement(name = "getChatroom", namespace = "http://com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getChatroom", namespace = "http://com/")

public class GetChatroom {


}

