
package com.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.3.13
 * Fri Mar 25 22:04:23 CST 2022
 * Generated source version: 3.3.13
 */

@XmlRootElement(name = "getChatMessageHistoryResponse", namespace = "http://com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getChatMessageHistoryResponse", namespace = "http://com/")

public class GetChatMessageHistoryResponse {

    @XmlElement(name = "return")
    private java.util.List<com.Message> _return;

    public java.util.List<com.Message> getReturn() {
        return this._return;
    }

    public void setReturn(java.util.List<com.Message> new_return)  {
        this._return = new_return;
    }

}

