
package com.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.3.13
 * Wed Mar 23 18:10:26 CST 2022
 * Generated source version: 3.3.13
 */

@XmlRootElement(name = "getRoomsResponse", namespace = "http://com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getRoomsResponse", namespace = "http://com/")

public class GetRoomsResponse {

    @XmlElement(name = "return")
    private java.util.List<com.Chatroom> _return;

    public java.util.List<com.Chatroom> getReturn() {
        return this._return;
    }

    public void setReturn(java.util.List<com.Chatroom> new_return)  {
        this._return = new_return;
    }

}

