
package com.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.3.13
 * Thu Mar 24 21:16:32 CST 2022
 * Generated source version: 3.3.13
 */

@XmlRootElement(name = "getUsers", namespace = "http://com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getUsers", namespace = "http://com/")

public class GetUsers {


}

