
package com.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.3.13
 * Mon Apr 11 04:05:27 CST 2022
 * Generated source version: 3.3.13
 */

@XmlRootElement(name = "mergeSortResponse", namespace = "http://com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "mergeSortResponse", namespace = "http://com/")

public class MergeSortResponse {

    @XmlElement(name = "return")
    private int[] _return;

    public int[] getReturn() {
        return this._return;
    }

    public void setReturn(int[] new_return)  {
        this._return = new_return;
    }

}

