
package com.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.3.13
 * Thu Mar 24 21:05:18 CST 2022
 * Generated source version: 3.3.13
 */

@XmlRootElement(name = "testRoomResponse", namespace = "http://com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "testRoomResponse", namespace = "http://com/")

public class TestRoomResponse {


}

