
package com.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.3.13
 * Mon Apr 11 03:41:02 CST 2022
 * Generated source version: 3.3.13
 */

@XmlRootElement(name = "testResponse", namespace = "http://com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "testResponse", namespace = "http://com/")

public class TestResponse {


}

